model_list:
  # --- Định nghĩa nhóm key cho gemini-2.5-pro-exp-03-25 ---
  # LiteLLM sẽ tự động luân phiên (round-robin) giữa các key này
  # Đặt cùng model_name để LiteLLM biết chúng thuộc cùng một nhóm
  - model_name: gemini-2.5-pro-exp-03-25-router # Tên định tuyến bạn sẽ gọi trong API
    litellm_params:
      model: gemini/gemini-2.5-pro-exp-03-25 # Model thực tế của Gemini
      api_key: os.environ/GEMINI_API_KEY_1
  - model_name: gemini-2.5-pro-exp-03-25-router # Cùng tên định tuyến
    litellm_params:
      model: gemini/gemini-2.5-pro-exp-03-25
      api_key: os.environ/GEMINI_API_KEY_2
  - model_name: gemini-2.5-pro-exp-03-25-router
    litellm_params:
      model: gemini/gemini-2.5-pro-exp-03-25
      api_key: os.environ/GEMINI_API_KEY_3
  - model_name: gemini-2.5-pro-exp-03-25-router
    litellm_params:
      model: gemini/gemini-2.5-pro-exp-03-25
      api_key: os.environ/GEMINI_API_KEY_4
  - model_name: gemini-2.5-pro-exp-03-25-router
    litellm_params:
      model: gemini/gemini-2.5-pro-exp-03-25
      api_key: os.environ/GEMINI_API_KEY_5
  - model_name: gemini-2.5-pro-exp-03-25-router
    litellm_params:
      model: gemini/gemini-2.5-pro-exp-03-25
      api_key: os.environ/GEMINI_API_KEY_6
  - model_name: gemini-2.5-pro-exp-03-25-router
    litellm_params:
      model: gemini/gemini-2.5-pro-exp-03-25
      api_key: os.environ/GEMINI_API_KEY_7
  - model_name: gemini-2.5-pro-exp-03-25-router
    litellm_params:
      model: gemini/gemini-2.5-pro-exp-03-25
      api_key: os.environ/GEMINI_API_KEY_8
  - model_name: gemini-2.5-pro-exp-03-25-router
    litellm_params:
      model: gemini/gemini-2.5-pro-exp-03-25
      api_key: os.environ/GEMINI_API_KEY_9
  - model_name: gemini-2.5-pro-exp-03-25-router
    litellm_params:
      model: gemini/gemini-2.5-pro-exp-03-25
      api_key: os.environ/GEMINI_API_KEY_10
  - model_name: gemini-2.5-pro-exp-03-25-router
    litellm_params:
      model: gemini/gemini-2.5-pro-exp-03-25
      api_key: os.environ/GEMINI_API_KEY_11
  - model_name: gemini-2.5-pro-exp-03-25-router
    litellm_params:
      model: gemini/gemini-2.5-pro-exp-03-25
      api_key: os.environ/GEMINI_API_KEY_12
  - model_name: gemini-2.5-pro-exp-03-25-router
    litellm_params:
      model: gemini/gemini-2.5-pro-exp-03-25
      api_key: os.environ/GEMINI_API_KEY_13
  - model_name: gemini-2.5-pro-exp-03-25-router
    litellm_params:
      model: gemini/gemini-2.5-pro-exp-03-25
      api_key: os.environ/GEMINI_API_KEY_14
  - model_name: gemini-2.5-pro-exp-03-25-router
    litellm_params:
      model: gemini/gemini-2.5-pro-exp-03-25
      api_key: os.environ/GEMINI_API_KEY_15
  - model_name: gemini-2.5-pro-exp-03-25-router
    litellm_params:
      model: gemini/gemini-2.5-pro-exp-03-25
      api_key: os.environ/GEMINI_API_KEY_16
  - model_name: gemini-2.5-pro-exp-03-25-router
    litellm_params:
      model: gemini/gemini-2.5-pro-exp-03-25
      api_key: os.environ/GEMINI_API_KEY_17
  - model_name: gemini-2.5-pro-exp-03-25-router
    litellm_params:
      model: gemini/gemini-2.5-pro-exp-03-25
      api_key: os.environ/GEMINI_API_KEY_18
  - model_name: gemini-2.5-pro-exp-03-25-router
    litellm_params:
      model: gemini/gemini-2.5-pro-exp-03-25
      api_key: os.environ/GEMINI_API_KEY_19
  - model_name: gemini-2.5-pro-exp-03-25-router
    litellm_params:
      model: gemini/gemini-2.5-pro-exp-03-25
      api_key: os.environ/GEMINI_API_KEY_20
  - model_name: gemini-2.5-pro-exp-03-25-router
    litellm_params:
      model: gemini/gemini-2.5-pro-exp-03-25
      api_key: os.environ/GEMINI_API_KEY_21
  - model_name: gemini-2.5-pro-exp-03-25-router
    litellm_params:
      model: gemini/gemini-2.5-pro-exp-03-25
      api_key: os.environ/GEMINI_API_KEY_22
  - model_name: gemini-2.5-pro-exp-03-25-router
    litellm_params:
      model: gemini/gemini-2.5-pro-exp-03-25
      api_key: os.environ/GEMINI_API_KEY_23
  - model_name: gemini-2.5-pro-exp-03-25-router
    litellm_params:
      model: gemini/gemini-2.5-pro-exp-03-25
      api_key: os.environ/GEMINI_API_KEY_24
  - model_name: gemini-2.5-pro-exp-03-25-router
    litellm_params:
      model: gemini/gemini-2.5-pro-exp-03-25
      api_key: os.environ/GEMINI_API_KEY_25
  - model_name: gemini-2.5-pro-exp-03-25-router
    litellm_params:
      model: gemini/gemini-2.5-pro-exp-03-25
      api_key: os.environ/GEMINI_API_KEY_26
  - model_name: gemini-2.5-pro-exp-03-25-router
    litellm_params:
      model: gemini/gemini-2.5-pro-exp-03-25
      api_key: os.environ/GEMINI_API_KEY_27
  - model_name: gemini-2.5-pro-exp-03-25-router
    litellm_params:
      model: gemini/gemini-2.5-pro-exp-03-25
      api_key: os.environ/GEMINI_API_KEY_28
  - model_name: gemini-2.5-pro-exp-03-25-router
    litellm_params:
      model: gemini/gemini-2.5-pro-exp-03-25
      api_key: os.environ/GEMINI_API_KEY_29
  - model_name: gemini-2.5-pro-exp-03-25-router
    litellm_params:
      model: gemini/gemini-2.5-pro-exp-03-25
      api_key: os.environ/GEMINI_API_KEY_30
  - model_name: gemini-2.5-pro-exp-03-25-router
    litellm_params:
      model: gemini/gemini-2.5-pro-exp-03-25
      api_key: os.environ/GEMINI_API_KEY_31
  - model_name: gemini-2.5-pro-exp-03-25-router
    litellm_params:
      model: gemini/gemini-2.5-pro-exp-03-25
      api_key: os.environ/GEMINI_API_KEY_32
  - model_name: gemini-2.5-pro-exp-03-25-router
    litellm_params:
      model: gemini/gemini-2.5-pro-exp-03-25
      api_key: os.environ/GEMINI_API_KEY_33
  - model_name: gemini-2.5-pro-exp-03-25-router
    litellm_params:
      model: gemini/gemini-2.5-pro-exp-03-25
      api_key: os.environ/GEMINI_API_KEY_34
  - model_name: gemini-2.5-pro-exp-03-25-router
    litellm_params:
      model: gemini/gemini-2.5-pro-exp-03-25
      api_key: os.environ/GEMINI_API_KEY_35
  - model_name: gemini-2.5-pro-exp-03-25-router
    litellm_params:
      model: gemini/gemini-2.5-pro-exp-03-25
      api_key: os.environ/GEMINI_API_KEY_36
  - model_name: gemini-2.5-pro-exp-03-25-router
    litellm_params:
      model: gemini/gemini-2.5-pro-exp-03-25
      api_key: os.environ/GEMINI_API_KEY_37
  - model_name: gemini-2.5-pro-exp-03-25-router
    litellm_params:
      model: gemini/gemini-2.5-pro-exp-03-25
      api_key: os.environ/GEMINI_API_KEY_38
  - model_name: gemini-2.5-pro-exp-03-25-router
    litellm_params:
      model: gemini/gemini-2.5-pro-exp-03-25
      api_key: os.environ/GEMINI_API_KEY_39
  - model_name: gemini-2.5-pro-exp-03-25-router
    litellm_params:
      model: gemini/gemini-2.5-pro-exp-03-25
      api_key: os.environ/GEMINI_API_KEY_40
  - model_name: gemini-2.5-pro-exp-03-25-router
    litellm_params:
      model: gemini/gemini-2.5-pro-exp-03-25
      api_key: os.environ/GEMINI_API_KEY_41
  - model_name: gemini-2.5-pro-exp-03-25-router
    litellm_params:
      model: gemini/gemini-2.5-pro-exp-03-25
      api_key: os.environ/GEMINI_API_KEY_42
  - model_name: gemini-2.5-pro-exp-03-25-router
    litellm_params:
      model: gemini/gemini-2.5-pro-exp-03-25
      api_key: os.environ/GEMINI_API_KEY_
  - model_name: gemini-2.5-pro-exp-03-25-router
    litellm_params:
      model: gemini/gemini-2.5-pro-exp-03-25
      api_key: os.environ/GEMINI_API_KEY_4343
  - model_name: gemini-2.5-pro-exp-03-25-router
    litellm_params:
      model: gemini/gemini-2.5-pro-exp-03-25
      api_key: os.environ/GEMINI_API_KEY_
  - model_name: gemini-2.5-pro-exp-03-25-router
    litellm_params:
      model: gemini/gemini-2.5-pro-exp-03-25
      api_key: os.environ/GEMINI_API_KEY_44
  - model_name: gemini-2.5-pro-exp-03-25-router
    litellm_params:
      model: gemini/gemini-2.5-pro-exp-03-25
      api_key: os.environ/GEMINI_API_KEY_45
  - model_name: gemini-2.5-pro-exp-03-25-router
    litellm_params:
      model: gemini/gemini-2.5-pro-exp-03-25
      api_key: os.environ/GEMINI_API_KEY_46
  - model_name: gemini-2.5-pro-exp-03-25-router
    litellm_params:
      model: gemini/gemini-2.5-pro-exp-03-25
      api_key: os.environ/GEMINI_API_KEY_47
  - model_name: gemini-2.5-pro-exp-03-25-router
    litellm_params:
      model: gemini/gemini-2.5-pro-exp-03-25
      api_key: os.environ/GEMINI_API_KEY_48

# (Tùy chọn) Bạn có thể thêm các cấu hình khác của LiteLLM ở đây
# ví dụ:
# general_settings:
#   master_key: sk-1234 # Nếu bạn muốn bảo vệ proxy bằng master key

# litigation:
#   # Các cài đặt log, v.v.
      
  # Thêm các model khác tương tự nếu muốn
  # - model_name: gemini-vision
  #   litellm_params:
  #     model: models/gemini-pro-vision # (Kiểm tra ID đúng)

litellm_settings:
  set_verbose: true
      # API keys sẽ được đọc từ biến môi trường bạn cài trên Render
      # (GEMINI_API_KEY_1, GEMINI_API_KEY_2, ...)

litellm_settings:
  set_verbose: true # Để xem log chi tiết trên Render
  drop_params: true
