model_list:
model_list:
  - model_name: Gemini-2.5-Pro-Experimental # <<< TÊN BẠN SẼ DÙNG trong SillyTavern
    litellm_params:
      model: gemini/gemini-2.5-pro-exp-03-25 # <<< ID MODEL THẬT sự của Google
      api_key: os.environ/GEMINI_API_KEY
  # Thêm các model khác tương tự nếu muốn
  # - model_name: gemini-vision
  #   litellm_params:
  #     model: models/gemini-pro-vision # (Kiểm tra ID đúng)

litellm_settings:
  set_verbose: true
      # API keys sẽ được đọc từ biến môi trường bạn cài trên Render
      # (GEMINI_API_KEY_1, GEMINI_API_KEY_2, ...)

litellm_settings:
  set_verbose: true # Để xem log chi tiết trên Render
  drop_params: true
